hash-format = "sha256"

[[files]]
file = "config/supplementaries-client.toml"
hash = "6c23e35580c0c92973bb80aa12addcf3a803e61187925625562bba78d22cb65b"

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "a246d31ff42f7c6d43841a065a4cd5144d7db70284993f0c614209ef49d37ad5"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "490897359704ec308c4a81ceb4105aacf0120d9a872111a5069f392fc5c88f2f"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "656dd3bff7bccd46e968b36de94e80d1f0a1e06da4d6a364f018d0dc2aa59475"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "a8184faf87506a1029e5e77f25e15568ec280e14451e9e9b19c6afdb9351950c"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "83739fed4e58e997b7aeb4eeda7319b30f57c4afc13d17b45f6d9fec881acd3e"
metafile = true
